name: gitcandies
description: A GitHub Flutter application.

version: 0.1.0+10

environment:
  sdk: ">=2.5.0 <3.0.0"
  flutter: ">=1.9.1+hotfix.4"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: 0.14.2
#  github: 5.4.0
  github:
    git: https://github.com/AlexVincent525/github.dart.git
  intl: any
  provider: 3.1.0+1
  pull_to_refresh_notification: 0.3.2
  shared_preferences: 0.5.3+4
  oktoast: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/candies/
    - assets/candies/logo/
    - assets/github/logos/
    - assets/github/mark/
    - assets/github/octocat/
    - assets/octicon/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #