name: gitav
description: A GitHub Flutter application.

version: 0.1.0+2

environment:
    sdk: ">=2.5.0 <3.0.0"
    flutter: 1.9.1+hotfix.4

dependencies:
    flutter:
        sdk: flutter
    github: 5.4.0
    provider: 3.1.0
    shared_preferences: 0.5.3+4

dev_dependencies:
    flutter_test:
        sdk: flutter


flutter:
    uses-material-design: true

    assets:
      - assets/github/logos/
      - assets/github/mark/
      - assets/github/octocat/

    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #