name: gitcandies
description: A GitHub Flutter application.

version: 0.1.0+14

environment:
  sdk: ">=2.5.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: 0.7.0
  flutter_svg: 0.15.0
  github: 6.0.3
  intl: any
  provider: 3.2.0
  pull_to_refresh_notification: 0.3.3
  shared_preferences: 0.5.6
  oktoast: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  ff_annotation_route: ^1.1.3+2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/candies/
    - assets/candies/logo/
    - assets/github/logos/
    - assets/github/mark/
    - assets/github/octocat/
    - assets/octicon/
