name: gitcandies
description: A GitHub Flutter application.

version: 0.1.0+13

environment:
  sdk: ">=2.5.0 <3.0.0"
  flutter: ">=1.9.1+hotfix.6"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: 0.14.3
#  github: 5.4.0
  github:
    git: https://github.com/AlexVincent525/github.dart.git
  intl: any
  provider: 3.1.0+1
  pull_to_refresh_notification: 0.3.2
  shared_preferences: 0.5.4+1
  oktoast: ^2.2.0
  flutter_screenutil: 0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  ff_annotation_route: ^1.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/candies/
    - assets/candies/logo/
    - assets/github/logos/
    - assets/github/mark/
    - assets/github/octocat/
    - assets/octicon/
