name: Issues Labeler
on:
  issues:
    types: [opened]

jobs:
  assignAlex:
    name: Assign Alex
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Assign Alex
        uses: actions/github@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: assign @alexvincent525
      - name: Apply pending confirm label
        uses: actions/github@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: label pending-confirm
      - name: Comment On New Issues
        uses: actions/github@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: comment "Thanks for submitting an issue! @alexvincent525 will take a look soon!"
